############################################
#                                          #
# Instructions: Comment lines with a "#"   #
#                                          #
############################################

###################
# Global Settings #
###################
[global]
ioengine=libaio
direct=1
rw=write
runtime=120

###################
# Seq RW Settings #
###################
bs=1M
iodepth=128
numjobs=2

####################
# Rand RW Settings #
####################
#bs=4k
#iodepth=32
#numjobs=8

##################
# Other Settings #
##################
#loops=99999
#size=40g
#cpus_allowed=0,1,2,3,4,5,6,7,8,9,10,11,12,13,14,15,16,17,18,19,20,21,22,23,24,25,26,27

#######################
# CPU 0 Bounded NVMes #
####################### 
[nvme0n1]
numa_cpu_nodes=0
numa_mem_policy=bind:0
filename=/dev/nvme0n1

#[/nvme1n1]
#numa_cpu_nodes=0
#numa_mem_policy=bind:0 
#filename=/dev/nvme1n1
#
#[/nvme2n1]
#numa_cpu_nodes=0
#numa_mem_policy=bind:0
#filename=/dev/nvme2n1
#
#[/nvme3n1]
#numa_cpu_nodes=0
#numa_mem_policy=bind:0 
#filename=/dev/nvme3n1
#
#[/nvme4n1]
#numa_cpu_nodes=0
#numa_mem_policy=bind:0 
#filename=/dev/nvme4n1
#
#[/nvme5n1]            
#numa_cpu_nodes=0
#numa_mem_policy=bind:0
#filename=/dev/nvme5n1
#
#[/nvme6n1]
#numa_cpu_nodes=0
#numa_mem_policy=bind:0
#filename=/dev/nvme6n1
#
#[/nvme7n1]
#numa_cpu_nodes=0
#numa_mem_policy=bind:0
#filename=/dev/nvme7n1
#
#[/nvme8n1]
#numa_cpu_nodes=0
#numa_mem_policy=bind:0
#filename=/dev/nvme8n1
#
#[/nvme9n1]
#numa_cpu_nodes=0
#numa_mem_policy=bind:0
#filename=/dev/nvme9n1
#
#[/nvme10n1]
#numa_cpu_nodes=0
#numa_mem_policy=bind:0
#filename=/dev/nvme10n1
#
#[/nvme11n1]
#numa_cpu_nodes=0
#numa_mem_policy=bind:0
#filename=/dev/nvme11n1

#######################
# CPU 1 Bounded NVMes #
#######################
#[/nvm12n1]
#numa_cpu_nodes=1
#numa_mem_policy=bind:1
#filename=/dev/nvme12n1
#
#[/nvme13n1]
#numa_cpu_nodes=1
#numa_mem_policy=bind:1
#filename=/dev/nvme13n1
#
#[/nvme14n1]
#numa_cpu_nodes=1
#numa_mem_policy=bind:1
#filename=/dev/nvme14n1
#
#[/nvme15n1]
#numa_cpu_nodes=1
#numa_mem_policy=bind:1
#filename=/dev/nvme15n1
#
#[/nvme16n1]
#numa_cpu_nodes=1
#numa_mem_policy=bind:1
#filename=/dev/nvme16n1
#
#[/nvme17n1]
#numa_cpu_nodes=1
#numa_mem_policy=bind:1
#filename=/dev/nvme17n1
#
#[/nvme18n1]
#numa_cpu_nodes=1
#numa_mem_policy=bind:1
#filename=/dev/nvme18n1
#
#[/nvme19n1]
#numa_cpu_nodes=1
#numa_mem_policy=bind:1
#filename=/dev/nvme19n1
#
#[/nvme20n1]
#numa_cpu_nodes=1
#numa_mem_policy=bind:1
#filename=/dev/nvme20n1
#
#[/nvme21n1]
#numa_cpu_nodes=1
#numa_mem_policy=bind:1
#filename=/dev/nvme21n1
#
#[/nvme22n1]
#numa_cpu_nodes=1
#numa_mem_policy=bind:1
#filename=/dev/nvme22n1
#
#[/nvme23n1]
#numa_cpu_nodes=1
#numa_mem_policy=bind:1
#filename=/dev/nvme23n1
